### ISSUE TITLE
სემინარების რესურსების და ჰენდაუთების სია

### ISSUE THREAD

**Issue by iarigby** [freeuni-paradigms/freeuni-paradigms.github.io#1]
ცხრილი გადავიდა აქ 
https://freeuni-paradigms.github.io/schedule.html

- [ ] 25- ნაკადების ბოლომდე
- [ ] 1-12

**Comment by iarigby** [comment]
@glekveishvili https://see.stanford.edu/materials/icsppcs107/03-Introducing-The-STL.pdf ამას როდის გავდივართ?

**Comment by iarigby** [comment]
ამ კვირას გვჭირდება მე-17 ჰენდაუთიდან ყველა, რომელიც სი (ნაკადების გარდა) და ესემბლის შეეხება.

**Comment by mdzam18** [comment]
ხუთშაბათისთვის თუ სულ ერთია როდისთვის იქნება კვირის ბოლომდე?

**Comment by iarigby** [comment]
ხუთშაბათს არაა აუცილებელი, პარასკევს თუ მზად იქნება (რამდენიმე ჰენდაუთია სულ, ნახევარი საათიც არ უნდა) კარგი იქნება.

**Comment by mdzam18** [comment]
გამარჯობა, მაინტერესებს, სად უნდა ავტვირთო ჰენდაუტების სია?  ასევე მაინტერესებს, სავარჯიშოებში ამოცანის სახელი მივუთითო? მაგალითად მე-20 ჰენდაუტში ასე უნდა ჩავწერო assembly (The Incredibles, New Zoo Revue)?

**Comment by iarigby** [comment]
ამ issue-ს ვერ უკეთებ edit-ს? ტექსტი სადაც წერია ზედა მარჯვენა კუთხეში

**Comment by mdzam18** [comment]
ააა, კი გავუკეთებ. მეგონა სხვაგან უნდა ამეტვირთა.

**Comment by mdzam18** [comment]
ყველაფერი სწორია, თუ შევცვალო რამე?

**Comment by iarigby** [comment]
@mdzam18 იდეალურადაა მადლობა

**Comment by iarigby** [comment]
@mdzam18 დავამატე შემდეგი რომელია საჭირო. პირდაპირ ფაილი დააედითე

**Comment by mdzam18** [comment]
25-ე ჰენდაუტამდეცაა ნაკადები და ისინიც ჩავამატო?

**Comment by iarigby** [comment]
კი

**Comment by mdzam18** [comment]
| სტატუსი  | ნომერი | სათაური | რა თემიდან არის, რა სავარჯიშოებია | 
|---|---|---|---|
| - | 1, 2 | | ~კურსის ინფორმაცია და და სილაბუსი~ | 
| [ ] | 3 | introducing the stl | |
| - | 4 | hw1 | c++ |
| - | 5 | ~unix basics~ | აქ mkddir, cd -ს გარდა სტენფორდის ექაუნთი და იმაკსია გარჩეული |
| [x] | 6 | bits and bytes |  |
| [x] | 7 | Arrays full story | c pointers, strcpy აქ იყო მგონი |
| [x] | 8 | the unix programming environment, gdb | make, compilation, g++ |
| [ ] | 9 | Assignment 2: Six Degrees of Kevin Bacon | c++ |
| [ ] | 9b | Assignment 2: Frequently Asked Questions | c++ |
| [ ] | 10 | Section Handout | c pointers. (Meet The Flintstones, Scheme) |
| [ ] | 10S | Section Solution | c pointers. (Meet The Flintstones, Scheme) |
| [ ] | 11 | Assignment 3: vector and hashset | c generics. (vector, hashset) |
| [ ] | 11b | Assignment 3: Frequently Asked Questions | c generics. (vector, hashset) |
| [ ] | 12 | Computer Architecture: Take I | assembly |
| [ ] | 13 | Computer Architecture: Take II | assembly |
| [ ] | 14 | Section Handout | c generics (The Generic Sorted Set) |
| [ ] | 14S | Section Solution | c generics (The Generic Sorted Set) |
| [ ] | 15 | Computer Architecture: Take III | assembly |
| [ ] | 16 | Computer Architecture: Take IV | assembly |
| [ ] | - | factorial trace | assembly |
| [ ] | 17 | Assignment 4: RSS News Feed Aggregation | c generics |
| [ ] | 17S | Assignment 4: Frequently Asked Questions | c generics |
| [ ] | 18 | Section Handout | c generics (sparseStringArray, serializeList, multitable, multitable client code) |
| [ ] | 18S | Section Solution |  c generics (sparseStringArray, serializeList, multitable, multitable client code) |
| [ ] | 19 | Assignment 5: Raw Memory | c generics , ბიტები, assembly, c++. (Binary numbers and bit operations, ASCII and extended ASCII, It's just bits and bytes, Identical Outputs, Find the linked list, Homestar Runner: The System Is Down, The Hitchhiker’s Guide To The Galaxy, C++’s Dark Side) |
| [ ] | 19S | Assignment 5 Solution | c generics, ბიტები, assembly, c++. (Binary numbers and bit operations, ASCII and extended ASCII, It's just bits and bytes, Identical Outputs, Find the linked list, Homestar Runner: The System Is Down, The Hitchhiker’s Guide To The Galaxy, C++’s Dark Side) |
| [ ] | 20 | Section Handout | assembly. (The Incredibles, New Zoo Revue) |
| [ ] | 20S | Section Solution | assembly. (The Incredibles, New Zoo Revue) |
| [ ] | 21 | CS107 Practice Midterm Exam | assembly, c pointers, c generics, ბიტები. (San Francisco Fine Dining, Breaking Larger Data Images Into Packets, The C multiset, The Queen Of Parking Infractions, Short Answers) |
| [ ] | 21S | CS107 Practice Midterm Solution | assembly, c pointers, c generics, ბიტები. (San Francisco Fine Dining, Breaking Larger Data Images Into Packets, The C multiset, The Queen Of Parking Infractions, Short Answers) |
| [ ] | 22 | CS107 Thread Package Documentation | threads |
| [ ] | 23 | Thread and Semaphore Examples | threads (Semaphores, Binary semaphores) |
| [ ] | 24 | Section Handout | c pointers, c generics, assembly (South of Market, Matchmaking, packPackets ) |
| [ ] | 24S | Section Solution | c pointers, c generics, assembly (South of Market, Matchmaking, packPackets ) |
| [ ] | 25 | CS107 Midterm Exam | assembly, c pointers, c generics, ბიტები. (Your Friendly Green Grocer, hashset, Take II, Decompressing Compressed Friend Graphs) |
| [ ] | 25S | CS107 Midterm Solution | assembly, c pointers, c generics, ბიტები. (Your Friendly Green Grocer, hashset, Take II, Decompressing Compressed Friend Graphs) |
| [ ] | 26 | More Concurrency | threads. (Semaphore Patterns, Binary lock, Generalized counter, Binary rendezvous, Generalized rendezvous, Layered construction, The Ice Cream Store Simulation |
| [ ] | 27 | Assignment 6: RSS News Search Revisited | threads |
| [ ] | 27b | Assignment 6: Frequently Asked Questions | threads |
| [ ] | 28 | Section Handout | threads (RSS News Feed Madness)|
| [ ] | 28S | Section Solution | threads (RSS News Feed Madness)|
| [ ] | 29 | Scheme Basics | scheme |
| [ ] | 30 | Defining Scheme Functions | scheme (factorial , fibonacci, fast-fibonacci, List Recursion, Quicksort)|
| [ ] | 31 | Scheme: Functions As Data | scheme (mergesort, mapping) |
| [ ] | 32 | Advanced Mapping, Apply, and Lambda | scheme (Power Sets, Permutations, Implementing map) |
| [ ] | 33 | Section Handout: All Things Scheme | scheme (Building Subsets of a Certain Size, Up Down Permutations) |
| [ ] | 33S | Section Solution: All Things Scheme | scheme (Building Subsets of a Certain Size, Up Down Permutations) |
| [ ] | 34 | Assignment 7: Where am I? | scheme |
| [ ] | 34b | Assignment 7: Frequently Asked Questions | scheme |
| [ ] | 35 | Python Basics | python |
| [ ] | 36 | Assignment 8: Tinkering With Python | python |
| [ ] | 37 | Python: XML, Sockets, Servers | python (Python SAX: Event Driven Parsing, DOM: Object-Based Parsing in Python, Simple Sockets: Building a Time Server) |
| [ ] | 38 | CS107 Final Exam Practice Problems | c++, c generics, c pointers, scheme, threads (Matchmaking, Extending the vector, C++ Spice Rack, Cars, Marriage And Mapping, Longest Common Subsequences, File Sharing, Concurrent, Short-Circuit Evaluation of Scheme’s and) |
| [ ] | 38S | CS107 Final Exam Practice Solution | c++, c generics, c pointers, scheme, threads (Matchmaking, Extending the vector, C++ Spice Rack, Cars, Marriage And Mapping, Longest Common Subsequences, File Sharing, Concurrent, Short-Circuit Evaluation of Scheme’s and) |
| [ ] | 39 | Section Handout: Python | python (Jane Austen’s Favorite Word, Maximizing Points, Python dictionary API) |
| [ ] | 39S | Section Solution: Python | python (Jane Austen’s Favorite Word, Maximizing Points) |

**Comment by mdzam18** [comment]
არ იყო ბევრი ჰენდაუტი დარჩენილი და ბარემ ყველა დავამატე. რამე ხომ არ გამომრჩა გასაკეთებელი? თუ სქემის და პითონის ჰენდაუტების დამატება სხვანაირად იყო საჭირო გადავაკეთებ.

**Comment by iarigby** [comment]
მადლობა^^ მგონი არა, ფაილში ჩაწერე ეგ ჰო? schedule.md

**Comment by mdzam18** [comment]
აა, არ ჩამიწერია. ვერ მივხვდი სად უნდა ჩავწერო.

**Comment by mdzam18** [comment]
schedule.md ეს ფაილი სადმე დევს?

**Comment by iarigby** [comment]
git pull გააკეთე.

საიტის ლინკები 1:1 შესაბამისობაშია დირექტორის სტრუქტურასთან, რა path იც
იქნა იგივეა რეპოზიტორიაშიც. და ყველა გვერდს აქვს view on github ღილაკი
ქვემოთ თუ არ ვცდები. საკმაოდ კომფორტული თემაა, ავტომატურად აგენერირებს მაგ
ყველაფერს.

**Comment by mdzam18** [comment]
ახლა ვნახე schedule.md ფაილი, ავტვირთავ მაშინ.

**Comment by mdzam18** [comment]
ჩავამატე ჩემი ცვლილებები schedule.md-ში და pull request დავამატე.
