### ISSUE TITLE
საცდელი სავარჯიშო 

### ISSUE THREAD

**Issue by iarigby** [freeuni-paradigms/freeuni-paradigms.github.io#10]
მე-18 ჰენდაუთში პირველი ამოცანა sparsestringarray და შემდეგ serializeList

ორმა ერთი გააკეთეთ, ორმა მეორე (კომენტარებში დაწერეთ რომელს აკეთებთ)

 [პირობა](https://see.stanford.edu/materials/icsppcs107/18-Section-Handout.pdf), [ამოხსნა](https://see.stanford.edu/materials/icsppcs107/18S-Section-Solution.pdf)

- დააკლონირეთ ეს რეპოზიტორია. შექმენით ახალი ბრენჩი `git checkout -b <username>-test-seminar`. დააკომიტეთ პროგრესი და `git push -u origin <branch-name>`. გახსენით pull request და დაამატეთ ამ issue-ზე `linked pull request`-ში (მარჯვნივ)
- სემინარის სავარჯიშოს ინსტრუქცია შეგიძლიათ ნახოთ `content/setup/index.md` ფაილში (შეგიძლიათ გახსნათ ლოკალურად ან [ონლაინ](https://freeuni-paradigms.github.io/content/setup/index.html))
- დაწყებამდე გადახედეთ წინა სავარჯიშოებს რომ წარმოდგენა შეგექმნათ. ყველგან იდენტურად არ არის ფორმატის ყველა პუნქტი დაცული, ახლა ჩამოვწერე ფორმატი სრულად

**Comment by iarigby** [comment]
@glekveishvili დაამატებს ტესტერის ფაილს და მაგალითს. მანამდე საწყისი ფაილები და ამოხსნის კომპილაციაზე შეგიძლიათ იმუშაოთ.

**Comment by iarigby** [comment]
fyi: ხვალ დიდი ალბათობით არ ვიქნები ხაზზე და ხუთშაბათ დილას გადავხედავ და სემინარამდე რომელიმეს დავმერჯავ

**Comment by glekveishvili** [comment]
აქ შეგიძლიათ ტესტის ფაილის მაგალითის ნახვა: https://gist.github.com/giolekva/d3684a265ddd9d451ce301397beb70af
დაგჭირდებათ ASSERT მაკროს და Test ფუნქციის კოპირება. რაღაც იდეები მაქვს გაუმჯობესებისთვის მაგრამ ჯობია თავიდან რაც შეიძლება მარტივით დავიწყოთ და საჭიროებისამებრ განვავრცოთ (ტესტირებისთვის საჭირო კოდი იმდენად რთული არ უნდა იყოს რომ სტუდენტმა მის გარჩევაში დახარჯოს ბევრი დრო)

**Comment by iarigby** [comment]
@gkhelo @d-chechelashvili ბევრი და დეტალური ტესტი იყო, მაგალითებიც კლიენტის კოდის ძალიან კარგი, ყოჩაღ
