### ISSUE TITLE
ლექცია-სემინარების ჩანაწერები

### ISSUE THREAD

**Issue by LukeSamkharadze** [freeuni-paradigms/freeuni-paradigms.github.io#11]
გამარჯობა 

ოფიციალურად ჩაწერილი ლექცია-სემინარების დრაივის ლინკი გვაქვს?

არსებობის შემთხვევაში, იქნებ ჩააგდოთ რეპოში სადმე

**Comment by iarigby** [comment]
მეც მაინტერესებს :smile: 

მივწერე აიტის და დავწერ რას მიპასუხებენ

**Comment by LukeSamkharadze** [comment]
რაიმე ახალი ხომ არ ისმის აიტიშნიკებისგან? :დ

**Comment by iarigby** [comment]
@LukeSamkharadze 
https://www.youtube.com/watch?v=NAEppFUWLfc

მგონი სტუდენტებს აქვთ ჩაწერილი და იქნებ გაიკითხო :დ
