### ISSUE TITLE
[საჩქარო] ხუთშაბათის სემინარი

### ISSUE THREAD

**Issue by iarigby** [freeuni-paradigms/freeuni-paradigms.github.io#18]
მე-18 ჰენდაუთში მე-3 და მე-4 ამოცანების გადატანა სავარჯიშოებში. ხუთშაბათამდე გვჭირდება, ამიტომ ვისაც დრო აქვს და შემდეგ ორ დღეში მოასწრებს, სჯობს იმან გააკეთოს

**Comment by mdzam18** [comment]
გამარჯობა, ტესტირებისათვის ვექტორისა და ჰეშსეტის კოდის გამოყენებაა საჭირო და vector.c და hashset.c-ც ავტვირთო?

**Comment by iarigby** [comment]
კი კი უნდა აგეტვირთა, გამომრჩა ეს მეილი.
