### ISSUE TITLE
Sparsestringarray_tests.c

### ISSUE THREAD

**Issue by LevanSamadashvili** [freeuni-paradigms/freeuni-paradigms.github.io#19]
sparsestringarray.c-სა და sparsestringarray_solution.c-ში მგონი ერთი სახელით წერია ფუნქციები(SSANew,...) და ტესტის კომპილირებისას ვერ კომპილირდება იმიტომ რომ ერთნაირი სახელებით წერია ფუნქციებიო.

**Comment by iarigby** [comment]
ერთად არ უნდა დაკომპილირდეს, solution მაგალითისთვის არის

**Comment by LevanSamadashvili** [comment]
მადლობა, სხვაგან ერთად სჭირდებოდა და მეგონა აქაც ეგრე იყო
