### ISSUE TITLE
sorted set-სტრუქტურის აღწერა

### ISSUE THREAD

**Issue by tsakh** [freeuni-paradigms/freeuni-paradigms.github.io#23]
sorted set-ს ტესტები არ მოყვება როგორც მივხვდი და იუზერის კოდის დაწერა გადავწყვიტე. რაღაც student struct-ი შევქმენი, რომელსაც ორი ველი აქვს: სახელი და ქულა. რადგან setNew-ს compare ფუნქციაც უნდა გავატანო, ეგ ფუნქციაც იუზერის კოდში ავღწერე (student struct-ის ქვემოთ) მაგრამ გადაცემული ვოიდ პოინტერების student*-ზე დაკასტვა რომ მინდა, ვერ ხედავს და ეგ რისი ბრალია?

**Comment by gkhelo** [comment]
სტრუქტურას როგორ აღწერ? 
struct student {

}; 
ასე თუ აღწერ შეიძლება მაგის ბრალი იყოს

**Comment by tsakh** [comment]
კი, მაგის ბრალი იყო. თუ ვინმეს დაჭირდება 
typedef struct {
}student;
ესე უნდა აღწეროთ (რატომ, არ ვიცი :დ)

**Comment by iarigby** [comment]
@tsakh 

https://stackoverflow.com/questions/252780/why-should-we-typedef-a-struct-so-often-in-c/252810
