### ISSUE TITLE
მე-4 დავალების დამატება

### ISSUE THREAD

**Issue by iarigby** [freeuni-paradigms/freeuni-paradigms.github.io#24]
- ნახეთ [საწყისი რეპოზიტორია](https://github.com/freeuni-paradigms/assn-template) და მიყევით ინსტრუქციას.
- ვინც რეპოზიტორიას შექმნის, დავალების რეპოზიტორიაზე ჩართეთ ნოთიფიკაციები და ახალ issue-ებს უპასუხეთ ხოლმე. თუ 1-2 დღეზე მეტი იქნებით offline, წინასწარ სხვა ლიდერს თხოვეთ რომ შეამოწმოს. კითხვები/პრობლემების მოგვარების შეჯამება (ის ნაწილები, რაც სხვებს მომავალში შეიძლება გამოადგეთ) პერიოდულად გადაიტანეთ ინსტრუქციაში (README ან faq) და დახურეთ issue-ბი

**Comment by glekveishvili** [comment]
აქ არ დაგვავიწყდეს, მეოთხე დავალებას პრობლემა ქონდა RSS feed-იდან remote URL ების გადმოწერა ვერ ხერხდებოდა libcurl + ssl -ის გამო მგონი.
ეგ არის გადასამოწმებელი და ან SSL-ის გარეშე ფიდებია მისაცემი ან საერთოდ ამოვაგდოთ remote ტესტები.
