### ISSUE TITLE
მე-3 დავალების დამატება

### ISSUE THREAD

**Issue by iarigby** [freeuni-paradigms/freeuni-paradigms.github.io#7]
- ნახეთ [საწყისი რეპოზიტორია](https://github.com/freeuni-paradigms/assn-template) და მიყევით ინსტრუქციას.
- ვინც რეპოზიტორიას შექმნის, დავალების რეპოზიტორიაზე ჩართეთ ნოთიფიკაციები და ახალ issue-ებს უპასუხეთ ხოლმე. თუ 1-2 დღეზე მეტი იქნებით offline, წინასწარ სხვა ლიდერს თხოვეთ რომ შეამოწმოს. კითხვები/პრობლემების მოგვარების შეჯამება (ის ნაწილები, რაც სხვებს მომავალში შეიძლება გამოადგეთ) პერიოდულად გადაიტანეთ ინსტრუქციაში (README ან faq) და დახურეთ issue-ბი

**Comment by iarigby** [comment]
@bes01 ყველაფერი კარგადაა მგონი, .pure ფაილი ვერ გავიგე ოღონდ რისია.  მთავარია შემდეგი ორი კვირა რამე პრობლემა თუ ქონდათ სკრიპტები/ინსტრუქცია/faq დააფდეითო. სკრიპტებზე დახმარება თუ დაგჭირდა დამთაგე.

**Comment by bes01** [comment]
.pure დავალებას მოყვა, არც მე ვიცი რისთვისაა😂
