### ISSUE TITLE
კონსულტაციის საათების დაგეგმვა

### ISSUE THREAD

**Issue by iarigby** [freeuni-paradigms/freeuni-paradigms.github.io#8]
სტუდენტებისთვის ერთი zoom ლინკი იქნება ხოლმე და ვისი ჯერიც იქნება შევა
- [ ] დრო გასარკვევი
- [ ] კალენდარის ივენთი 
- [ ] ამის შემდეგ მთავარ გვერდზეც უნდა დაემატოს ინფორმაცია, როგორც ლექცია სემინარები არის ჩასმული.

აქ დავამატოთ სია და თქვენით შეავსეთ ვინ როდის ჩაატარებს

**Comment by glekveishvili** [comment]
https://github.com/freeuni-paradigms/freeuni-paradigms.github.io/commit/62a6a2d78b142d6e69e0c0c90929a203fe6674bf
